name: app

type: "python:3.11"

variables:
  env:
    ENVIRONMENT: production
    POETRY_VERSION: "1.6.1"
    POETRY_VIRTUALENVS_IN_PROJECT: true
    POETRY_VIRTUALENVS_CREATE: true
    PIP_DISABLE_PIP_VERSION_CHECK: true

disk: 2048

hooks:
  build: |
    set -eu
    python3.11 -m pip install --upgrade pip
    export PIP_USER=false
    curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
    export PATH="/app/.local/bin:$PATH"
    export PIP_USER=true
    poetry install
    poetry add gunicorn@21.2.0
    npm install
    npm run build
    mkdir app/static/assets
    cp -r node_modules/@nationalarchives/frontend/nationalarchives/assets/* app/static/assets

web:
  upstream:
    socket_family: unix
  commands:
    start: "poetry run gunicorn etna:app --bind unix:$SOCKET --capture-output  --log-level debug"
  locations:
    "/":
      root: ""
      passthru: true
      allow: false
    "/static":
      headers:
        Access-Control-Allow-Origin: "*"
      root: static
      expires: 1y
      allow: true

mounts:
  tmp:
    source: local
    source_path: tmp

crons:
  renewcert:
    spec: "0 4 1,15 * *"
    cmd: |
      if [ "$PLATFORM_BRANCH" = main ]; then
        platform redeploy --yes --no-wait
      fi
