services:
  app:
    build:
      context: .
      args:
        IMAGE_TAG: preview
    environment:
      - ENVIRONMENT=develop
      - CONFIG=config.Develop
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - WAGTAIL_API_URL=http://host.docker.internal:8000/api/v2
      - SEARCH_API_URL=http://host.docker.internal:65534/api/v1
      - COOKIE_DOMAIN=localhost
      - CSP_IMG_SRC='self',localhost:65535,localhost:8000,*.google-analytics.com,*.googletagmanager.com,googletagmanager.com,*.gstatic.com,*.nationalarchives.gov.uk,*.platformsh.site
      - CSP_SCRIPT_SRC='self',*.googletagmanager.com,googletagmanager.com,tagmanager.google.com
      - CSP_STYLE_SRC='self',fonts.googleapis.com,p.typekit.net,use.typekit.net,googletagmanager.com,www.googletagmanager.com,tagmanager.google.com
      - CSP_FONT_SRC='self',fonts.gstatic.com,use.typekit.net
      - CSP_CONNECT_SRC='self',*.google-analytics.com,*.analytics.google.com,*.googletagmanager.com
      - CSP_MEDIA_SRC='self',localhost:8000
      - FRAME_DOMAIN_ALLOW=localhost:8000
      - GA4_ID=GTM-KX8ZWVZG
    ports:
      - 65535:8080
    volumes:
      - ./:/app

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:latest
    volumes:
      - ./:/app
