services:
  app:
    build:
      context: .
      args:
        IMAGE_TAG: preview
    environment:
      - ENVIRONMENT=develop
      - CONFIG=config.DevelopmentConfig
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - WAGTAIL_API_URL=http://host.docker.internal:8000/api/v2
      - SEARCH_API_URL=http://host.docker.internal:65534/api/v1
      - DOMAIN=localhost:65535
      - MEDIA_DOMAIN=localhost:8000
      - WAGTAIL_DOMAIN=localhost:8000
      - GA4_ID=GTM-KX8ZWVZG
    ports:
      - 65535:8080
    volumes:
      - ./:/app

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:latest
    volumes:
      - ./:/app
