services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python
        IMAGE_TAG: preview
    environment:
      - ENVIRONMENT=develop
      - CONFIG=config.Develop
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - WAGTAIL_API_URL=http://host.docker.internal:8000/api/v2
      - COOKIE_DOMAIN=localhost
      - CSP_IMG_SRC='self',localhost:65535,localhost:8000,*.google-analytics.com,*.googletagmanager.com,googletagmanager.com,*.gstatic.com,*.nationalarchives.gov.uk,*.platformsh.site,i.ytimg.com,loremflickr.com,picsum.photos,fastly.picsum.photos,
      - CSP_SCRIPT_SRC_ELEM='self',*.googletagmanager.com,googletagmanager.com,tagmanager.google.com,*.sentry-cdn.com,www.youtube.com
      - CSP_STYLE_SRC='self',fonts.googleapis.com,p.typekit.net,use.typekit.net,googletagmanager.com,www.googletagmanager.com,tagmanager.google.com
      - CSP_FONT_SRC='self',fonts.gstatic.com,use.typekit.net
      - CSP_CONNECT_SRC='self',*.google-analytics.com,*.analytics.google.com,*.googletagmanager.com,*.sentry.io,noembed.com
      - CSP_MEDIA_SRC='self',localhost:8000
      - CSP_WORKER_SRC='self',blob:,localhost:65535
      - CSP_FRAME_SRC='self',www.youtube-nocookie.com
      - CSP_FEATURE_PICTURE_IN_PICTURE='self',https://www.youtube-nocookie.com
      - FRAME_DOMAIN_ALLOW=localhost:8000
      - FEATURE_PHASE_BANNER=False
      - WAGTAILAPI_LIMIT_MAX=1000
    ports:
      - 65535:8080
    volumes:
      - ./:/app

  dev:
    image: ghcr.io/nationalarchives/tna-python-dev:preview
    volumes:
      - ./:/app
      - ../ds-wagtail:/app/tmp/ds-wagtail
