"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false
        default_ttl: 300
        cookies:
            - cookies_policy
            - cookie_preferences_set
        headers:
            - Accept
            - Vary

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"
