name: Get version tag

outputs:
  version-tag:
    description: "Version tag"
    value: ${{ steps.version-tag.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - id: version-tag
      name: Get tag from branch, tag or release
      run: |
        # VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        VERSION=$(echo "${{ github.event.ref }}" | sed -e 's,[\./_],-,g')
        echo "Basic version:                $VERSION"

        # Strip "v" prefix from tag name
        [[ "${{ github.ref_type }}" == "tag" ]] && VERSION=$(echo "$VERSION" | sed -e 's/^v//')
        echo "Tag version without v prefix: $VERSION"

        CALVER=$(date +%y.%m.%d).${{ github.run_number }}
        echo "Calver:                       $CALVER"
        [ "$VERSION" == "main" ] && VERSION=$CALVER
        # TEMP
        [ "$VERSION" == "proof-of-concept" ] && VERSION=$CALVER
        echo "Final version:                $VERSION"

        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
