name: Get version tag

outputs:
  version-tag:
    description: "Version tag"
    value: ${{ steps.version-tag.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - id: version-tag
      name: Get tag from branch, tag or release
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref_type }}" == "tag" ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [[ "${{ github.ref_type }}" == "branch" ]] && VERSION=$(echo "${{ github.ref }}" | sed -e 's,refs/heads/,,g') | sed -e 's,/,-,g'
        CALVER=$(date +%y.%m.%d).${{ github.run_number }}
        [ "$VERSION" == "main" ] && VERSION=$CALVER
        # TEMP
        [ "$VERSION" == "proof-of-concept" ] && VERSION=$CALVER
        echo "Version: $VERSION"
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
