name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - proof-of-concept

concurrency:
  group: cd

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run tests
        run: poetry run python -m pytest --ignore=test/integration/ds-wagtail

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: version-tag
        uses: ./.github/actions/get-version-tag
      - name: Build Docker image
        uses: ./.github/actions/docker-build
        with:
          version: ${{ steps.version-tag.outputs.version-tag }}
          latest: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: ${{ vars.DOCKER_IMAGE_NAME }}
